### ISSUE TITLE
Firebase.js configuration thanks

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [MartsTech/tinder-clone#1]
Firebase.js configuration thanks
What is the configuration of firebase.js I am taking this project to learn and add features
Thanks a lot

**Comment by MartsTech** [comment]
@HoracioLopezCarvajal Thank you for taking notice of my project! I'll write you same instructions of how to get your firebase config and how to add them in your project. Sorry if it is not exactly what you needed and feel free to ask me again if so.

1. You should go to the [firebase](https://console.firebase.google.com/), add a new project, unable google auth, unable firestore and get your project config. 
2. Then go in the expo folder of the project and find the `.env.example`  and raname it to `.env`. There you can paste your firebase config.
3. For the `GOOGLE_WEB_CLIENT_ID` go again in [firebase](https://console.firebase.google.com/), in authentication and find Sign-in methods. Click on the Google Provider and then on Web SDK configuration. There should be the web client id.
4. That is the setup, the env values are then used in the [firebase.ts](https://github.com/MartsTech/tinder-clone/blob/main/expo/src/utils/firebase.ts) file, where you could also paste your firebase config if you don't worry about exposing them in github for example.

Hope It helped you and again feel free to ask me if this is not your issue.

**Comment by HoracioLopezCarvajal** [comment]
Thank you very much I will upload project updates with new features. You
are invited to the days you want full board to Marbella.
+34692110212
